# Generated by Django 3.1.7 on 2021-02-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('salary', models.IntegerField(default=-1)),
                ('experience', models.IntegerField()),
                ('company', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('jobtitle', models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.jobtitle')),
            ],
        ),
    ]
