# Generated by Django 3.1.7 on 2021-02-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Inteview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('jobtitle', models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.jobtitle')),
            ],
        ),
    ]
