# Generated by Django 3.1.7 on 2021-02-23 07:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210223_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
