# Generated by Django 3.1.7 on 2021-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
