# Generated by Django 3.1.7 on 2021-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_interview_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['draft']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=300),
        ),
    ]
