# Generated by Django 3.1.7 on 2021-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210223_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
