# Generated by Django 3.1.7 on 2021-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
