# Generated by Django 3.1.7 on 2021-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_job_apply_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
