# Generated by Django 3.1.7 on 2021-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210316_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date', '-salary', 'experience']},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='job',
            name='part_time',
            field=models.BooleanField(default=False),
        ),
    ]
