# Generated by Django 3.1.7 on 2021-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210325_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='jobtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
